service: hour-logger

frameworkVersion: '2'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  environment:
    userTable: ${env:userTable}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamobd:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
      
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: false
    packager: 'yarn'
    excludeFiles: src/**/*.test.js

functions:
  create-user:
    handler: src/handlers/users.createUser
    memorySize: 128
    description: "Creates user"
    events:
      - http:
            path: users/create
            method: post
            authorizer: aws_iam
            cors: true
  
  get-user:
    handler: src/handlers/users.getUser
    memorySize: 128
    description: "Gets current user informations"
    events:
      - http:
            path: users/me
            method: get
            authorizer: aws_iam
            cors: true
  
  # get-hours:
  #   handler: handler.hours
  #   memorySize: 128
  #   description: "Gets user's hours"
  #   events:
  #     - http:
  #           path: users/hours
  #           method: get
  #           authorizer: aws_iam
  #           cors: true
  
  # edit-hours:
  #   handler: handler.editHours
  #   memorySize: 128
  #   description: "Edit user's hours"
  #   events:
  #     - http:
  #           path: users/hours
  #           method: post
  #           authorizer: aws_iam
  #           cors: true

resources:
  Resources:
    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "userId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "userId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.userTable}
