service: hour-logger

frameworkVersion: '2'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  environment:
    userTable: ${env:userTable}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "*"
      
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
    packager: 'yarn'
    excludeFiles: src/**/*.test.js

functions:
  create-user:
    handler: src/handlers/users.createUser
    memorySize: 128
    description: "Creates user"
    events:
      - http:
            path: /users
            method: post
            # authorizer: aws_iam
            cors: true
  
  get-user:
    handler: src/handlers/users.getUser
    memorySize: 128
    description: "Gets current user informations"
    events:
      - http:
            path: /users/{userId}
            method: get
            cors: true
            request: 
              parameters: 
                paths: 
                  userId: true

  get-users:
    handler: src/handlers/users.getAllUsers
    memorySize: 128
    description: "Gets all user information"
    events:
      - http:
            path: /users
            method: get
            cors: true

  check-in:
    handler: src/handlers/hours.checkIn
    memorySize: 128
    description: "Creates new hour transaction"
    events:
      - http:
            path: /users/check-in
            method: post
            # authorizer: aws_iam
            cors: true

resources:
  Resources:
    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "userId"
            AttributeType: "S"
          -
            AttributeName: "studentNumber"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "userId"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          - IndexName: StudentNumberIndex
            KeySchema:
              - AttributeName: studentNumber
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.userTable}
