name: Pull Request Deployment 🛠️

on:
  pull_request:
    paths:
      - 'api/**'
      - 'integration/**'
      - '.github/**'

jobs:
  testAndDeployLambda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      api-directory: ./api
      integration-directory: './integration'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Dependencies
        run: yarn
        working-directory: ${{ env.api-directory }}

      - name: Run Unit Tests
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          threshold: 70
          working-directory: ${{ env.api-directory }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Lambda Deployment
        run: |
          serverless deploy --stage=beta
        working-directory: ${{ env.api-directory }}

      - name: API Integration Tests
        run: |
          cd $GITHUB_WORKSPACE
          npx newman run integration/integration.postman_collection.json -e integration/environment.json
